{ config, pkgs, ... }:
let
  vim-solarized8 = pkgs.vimUtils.buildVimPluginFrom2Nix {
    pname = "vim-solarized8";
    version = "2022-05-03";
    src = pkgs.fetchFromGitHub {
      owner = "lifepillar";
      repo = "vim-solarized8";
      rev = "9f9b7951975012ce51766356c7c28ba56294f9e8";
      sha256 = "1qg9n6c70jyyh38fjs41j9vcj54qmhkkyzna0la7bwsycqfxbs2x";
    };
  };

in
{
  imports = [
    ./languageclient.nix
    ./vim-fugitive.nix
  ];
  programs.neovim = {
    enable = true;
    viAlias = true;
    vimAlias = true;
    extraConfig = builtins.readFile ./extraConfig.vim;
    plugins = with pkgs.vimPlugins; [
      vim-solarized8
      vim-nix
      vim-dispatch
      vim-obsession
    ];
  };
  programs.git.ignores = [
    "Session.vim" # generated by vim-obsession
  ];
}
